version: '3.8'

# Production overrides for docker-compose.yml

services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile.prod
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile.prod
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

  mysql:
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password --innodb-buffer-pool-size=512M
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  redis:
    restart: unless-stopped
    command: redis-server --maxmemory 256mb --maxmemory-policy allkeys-lru
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  # Remove development-only services
  mailhog:
    profiles:
      - dev

  node:
    profiles:
      - dev